project:
  type: website

website:
  title: "Roberto García Martín - Trabajo Fin de Máster"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/roberto-garcia-martin/

format:
  html:
    theme: cosmo
    css: styles.css
editor: 
  render-on-save: true



